[package]
name = "rusalka"
version = "1.0.0"
edition = "2021"
description = "A 3D Perlin Noise Generator"
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.8.5"
rand_seeder = "0.2.3"
rand_pcg = "0.3.1"
